{
    'name': 'Hospital Module',
    'version': '1.0',
    'category': 'Industry',
    'summary': 'Hospital System',
    'description': "Hospital system to manage patients, Doctors, Appointments, Reports",
    'author': 'Sherif Ali',
    'license': 'LGPL-3',
    'data': [
        'views/patient_view.xml',
        'views/doctor_view.xml',
        'views/appointment_view.xml',
        'views/appointment_slot_view.xml',
        'views/control_panel.xml',
        'views/message_wizard.xml',
        'views/menu_items.xml',
        'views/today_appointment_template.xml',
        'views/today_slot_template.xml',
        'views/cus_auth.xml',
        'security/ir.model.access.csv',
        'report/hospital_doctor_report.xml',
        'report/hospital_patient_report.xml',
        'report/hospital_appointment_slot_report.xml',
        'report/hospital_appointment_report.xml',
        'report/hospital_appointment_analyze_report.xml',
    ],
    'assets': {
        'web.assets_backend': ['hospital_module/static/src/css/custom_styles.css', ]
    },
    'installable': True,
    'auto_install': False,
    'application': True,
    'depends': ['base'],
    'demo': [],
}
